<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Material Densities (kg/m^3) - 600 is stable for simulation -->
    <xacro:property name="d1" value="600.0"/> 
    <xacro:property name="d2" value="600.0"/> 
    <xacro:property name="d3" value="600.0"/>

    <!-- Mass Calculations -->
    <xacro:property name="m1" value="${d1 * a * b * c}"/>
    <xacro:property name="m2" value="${d2 * pi * r * r * d}"/>
    <xacro:property name="m3" value="${d3 * (4/3) * pi * cr * cr * cr}"/>

    <!-- Body Inertia Moments (Box) -->
    <xacro:property name="Ix_body" value="${m1 * (b*b + c*c) / 12}" />
    <xacro:property name="Iy_body" value="${m1 * (a*a + c*c) / 12}" />
    <xacro:property name="Iz_body" value="${m1 * (a*a + b*b) / 12}" />

    <!-- Wheel Inertia Moments (Cylinder) -->
    <!-- When cylinder is rotated pi/2 on X, Iz becomes the rolling axis -->
    <xacro:property name="Iz_wheel" value="${0.5 * m2 * r * r}" />
    <xacro:property name="I_wheel" value="${(1.0/12.0) * m2 * (3.0*r*r + d*d)}" />

    <!-- Caster Inertia Moments (Sphere) -->
    <xacro:property name="I_caster" value="${(2.0/5.0) * m3 * cr * cr}" />
    <!--lidar specification -->
<xacro:property name="I_lidar_x" value="${(1/12) * laser_m * (3*laser_r*laser_r + laser_l*laser_l)}"/>
<xacro:property name="I_lidar_y" value="${(1/12) * laser_m * (3*laser_r*laser_r + laser_l*laser_l)}"/>
<xacro:property name="I_lidar_z" value="${(1/2) * laser_m * (laser_r*laser_r)}"/>

    <!-- BODY INERTIA MACRO -->
    <xacro:macro name="inertial_body">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 ${c/2}" />
            <mass value="${m1}" />
            <inertia ixx="${Ix_body}" ixy="0.0" ixz="0.0"
                     iyy="${Iy_body}" iyz="0.0"
                     izz="${Iz_body}" />
        </inertial>
    </xacro:macro>

    <!-- WHEEL INERTIA MACRO -->
    <xacro:macro name="inertial_wheel">
        <inertial>
            <!-- Important: Orientation of mass must match visual orientation -->
            <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
            <mass value="${m2}" />
            <inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0"
                     iyy="${I_wheel}" iyz="0.0"
                     izz="${Iz_wheel}" />
        </inertial>
    </xacro:macro>

    <!-- CASTER INERTIA MACRO -->
    <xacro:macro name="inertial_caster">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="${m3}" />
            <inertia ixx="${I_caster}" ixy="0.0" ixz="0.0"
                     iyy="${I_caster}" iyz="0.0"
                     izz="${I_caster}" />
        </inertial>
    </xacro:macro>
   <!-- LIDAR INERTIA MACRO -->
    <!-- Macro for LiDAR/Cylinder Inertia -->
    <!-- LIDAR INERTIA MACRO -->
<xacro:macro name="inertial_lidar">
  <inertial>
    <origin xyz="0 0 ${laser_l/2}" rpy="0 0 0"/>
    <!-- Mass of the LiDAR sensor -->
    <mass value="${laser_m}"/>
    <!-- Approximate inertia values for a small cylindrical sensor -->
    <inertia ixx="${I_lidar_x}" ixy="0.0" ixz="0.0"
             iyy="${I_lidar_y}" iyz="0.0"
             izz="${I_lidar_z}"/>
  </inertial>
</xacro:macro>


</robot>
